imports:
    - php
    - javascript

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    php_sim: true
    php_cpd: false
    js_hint: true

filter:
    excluded_paths: [includes/*, vendor/*, tests/*, app/*, bin/*, library/*]
