imports:
    - php
    - js

tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true
    js_hint: true

filter:
    excluded_paths: [includes/*, vendor/*, tests/*, app/*, bin/*, library/*]
