language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script: bash -xe tests/initialize.sh

script: tests/runTests.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc: "irc.freenode.org##alezakos"
