language: php
php:
  - 5.5
  - 5.4
  - 5.3

install:
 - curl -sS https://getcomposer.org/installer | php
 - php composer.phar install --no-interaction

before_script: bash -xe tests/initialize.sh

script: tests/runTests.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  webhooks:
    - http://helit.org:8093/+sujevo/showSuccessfulBuildMessages=on_change
    - http://helit.org:8093/++alezakos/showSuccessfulBuildMessages=always
