framework:
    secret: "toast"
    router:
        resource: "%kernel.root_dir%/routes.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme

services:
    main.warmer.twig_warmer:
        class: TwigCacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
