BZIon\Bundle\Entity\BannedIP:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ipAddress:
            type: string
            length: '15'
            column: ip_address
    manyToOne:
        ban:
            targetEntity: Ban
            inversedBy: ips
    lifecycleCallbacks: {  }
