BZIon\Bundle\Entity\NewsCategory:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        alias:
            type: string
            length: '32'
            unique: true
            nullable: true
        name:
            type: string
            length: '50'
        protected:
            type: boolean
        status:
            type: string
            length: '32'
    oneToMany:
        articles:
            targetEntity: NewsArticle
            mappedBy: category
    lifecycleCallbacks: {  }
