BZIon\Bundle\Entity\NewsArticle:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            length: '100'
        content:
            type: text
        created:
            type: datetime
        updated:
            type: datetime
        status:
            type: string
            length: '32'
    manyToOne:
        author:
            targetEntity: Player
            joinColumn:
                nullable: false
        editor:
            targetEntity: Player
            joinColumn:
                nullable: false
        category:
            targetEntity: NewsCategory
            inversedBy: articles
            joinColumn:
                nullable: false
        parent:
            targetEntity: NewsArticle
            inversedBy: children
    oneToMany:
        children:
            targetEntity: NewsArticle
            mappedBy: parent
    lifecycleCallbacks: {  }
