BZIon\Bundle\Entity\Page:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '32'
        alias:
            type: string
            length: '32'
        content:
            type: text
        created:
            type: datetime
        updated:
            type: datetime
        status:
            type: string
            length: '32'
    manyToOne:
        author:
            targetEntity: Player
            joinColumn:
                nullable: false
        parent:
            targetEntity: Page
            inversedBy: children
    oneToMany:
        children:
            targetEntity: Page
            mappedBy: parent
    lifecycleCallbacks: {  }
