BZIon\Bundle\Entity\PastCallsign:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '32'
    manyToOne:
        player:
            targetEntity: Player
            inversedBy: pastCallsigns
            joinColumn:
                nullable: false
    lifecycleCallbacks: {  }
