index:
    pattern:  /
    defaults: { _controller: 'Home', _action: 'show' }

admin_list:
    pattern:    /admins
    defaults: { _controller: 'Admin', _action: 'list' }

ban_list:
    pattern:    /bans
    defaults: { _controller: 'Ban', _action: 'list' }

ban_show:
    pattern:    /bans/{ban}
    defaults: { _controller: 'Ban', _action: 'show' }

login:
    pattern:    /login
    defaults: { _controller: 'Login', _action: 'login' }

logout:
    pattern:    /logout
    defaults: { _controller: 'Login', _action: 'logout' }

match_list:
    pattern:    /matches
    defaults: { _controller: 'Match', _action: 'list' }

match_by_team_list:
    pattern:    /teams/{team}/matches
    defaults: { _controller: 'Match', _action: 'listByTeam' }

match_by_team_list_sort:
    pattern:    /teams/{team}/matches/{type}
    defaults: { _controller: 'Match', _action: 'listByTeamSort' }

match_enter:
    pattern:    /matches/enter
    defaults: { _controller: 'Match', _action: 'create' }

message_list:
    pattern:    /messages
    defaults: { _controller: 'Message', _action: 'compose' }

message_show_discussion:
    pattern:    /messages/{discussion}
    defaults: { _controller: 'Message', _action: 'show' }

news_list:
    pattern:    /news
    defaults: { _controller: 'News', _action: 'list' }

news_show:
    pattern:    /news/{article}
    defaults: { _controller: 'News', _action: 'show' }

news_category_show:
    pattern:    /news/category/{category}
    defaults: { _controller: 'News', _action: 'list' }

player_list:
    pattern:    /players
    defaults: { _controller: 'Player', _action: 'list' }

player_show:
    pattern:    /players/{player}
    defaults: { _controller: 'Player', _action: 'show' }

profile_show:
    pattern:    /profile
    defaults: { _controller: 'Profile', _action: 'show' }

profile_edit:
    pattern:    /profile/edit
    defaults: { _controller: 'Profile', _action: 'edit' }

server_list:
    pattern:    /servers
    defaults: { _controller: 'Server', _action: 'list' }

team_list:
    pattern:    /teams
    defaults: { _controller: 'Team', _action: 'list' }

team_show:
    pattern:    /teams/{team}
    defaults: { _controller: 'Team', _action: 'show' }

team_members:
    pattern:    /teams/{team}/members
    defaults: { _controller: 'Player', _action: 'list' }

team_delete:
    pattern:    /teams/{team}/delete
    defaults: { _controller: 'Team', _action: 'delete' }

team_kick:
    pattern:    /teams/{team}/kick/{player}
    defaults: { _controller: 'Team', _action: 'kick' }

team_abandon:
    pattern:    /teams/{team}/abandon
    defaults: { _controller: 'Team', _action: 'abandon' }

custom_page:
    pattern:    /{page}
    defaults: { _controller: 'Page', _action: 'show' }

trailing_slash:
    path: /{url}
    defaults: { _controller: 'Redirecting', _action: 'removeTrailingSlash' }
    methods: [GET]
    requirements:
        url: .*/$
