framework:
    secret: "toast"
    router:
        resource: "%kernel.root_dir%/routes.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
    session:
        handler_id: ~

monolog:
    channels: ["api"]
    handlers:
        api:
            type: stream
            # TODO: Store the path on the config file
            path: "%kernel.root_dir%/logs/api.log"
            level: notice
            channels: [api]
        main:
            type: stream
            path: "%kernel.root_dir%/logs/main.log"
            level: notice
            channels: [app]

services:
    main.warmer.twig_warmer:
        class: BZIon\Twig\TwigCacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
    bzion.command.install_command:
        class: BZIon\Command\InstallCommand
        tags:
            -  { name: console.command }
    bzion.command.update_command:
        class: BZIon\Command\UpdateCommand
        tags:
            -  { name: console.command }
    bzion.command.config_command:
        class: BZIon\Command\ConfigCommand
        tags:
            -  { name: console.command }
    bzion.command.server_command:
        class: BZIon\Command\ServerCommand
        tags:
            -  { name: console.command }
