imports:
    - {  resource: "bzion_config_bridge.php" }

framework:
    secret: "toast"
    router:
        resource: "%kernel.root_dir%/routes.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
    session:
        handler_id: ~

monolog:
    channels: ["app", "api", "mysql"]
    handlers:
        api:
            type: stream
            path: "%bzion.log.dir%/api.log"
            level: %bzion.log.level%
            channels: [api]
        main:
            type: stream
            path: "%bzion.log.dir%/main.log"
            level: %bzion.log.level%
            channels: [app, mysql]

services:
    main.warmer.twig_warmer:
        class: BZIon\Twig\TwigCacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
    kernel.subscriber.bzion_subscriber:
        class: BZIon\Event\EventSubscriber
        arguments: [@mailer]
        tags:
            - { name: kernel.event_subscriber }
    bzion.command.install_command:
        class: BZIon\Command\InstallCommand
        tags:
            -  { name: console.command }
    bzion.command.config_command:
        class: BZIon\Command\ConfigCommand
        tags:
            -  { name: console.command }
    bzion.command.changes_command:
        class: BZIon\Command\ChangesCommand
        tags:
            -  { name: console.command }
    bzion.command.server_command:
        class: BZIon\Command\ServerCommand
        tags:
            -  { name: console.command }
