imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        handler_id: ~
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/Resource/routes_test.yml"
