framework:
    secret: "toast"
    router:
        resource: "%kernel.root_dir%/routes.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme

services:
    main.warmer.twig_warmer:
        class: TwigCacheWarmer
        tags:
            - { name: kernel.cache_warmer, priority: 0 }
    bzion.command.install_command:
        class: Command\InstallCommand
        tags:
            -  { name: console.command }
    bzion.command.update_command:
        class: Command\UpdateCommand
        tags:
            -  { name: console.command }
